### ISSUE TITLE
Unable to import Bookmark

### ISSUE THREAD

**Issue by nitin194** [reetasingh/CKAD-Bookmarks#2]
Hello Reeta,

Thank you so much for compiling this set of bookmarks for the CKA* set of exams. But I am unable to import them in the chrome browser. I mean folder or bookmark link doesn't show up after importing the file. Am I missing some step?

**Comment by reetasingh** [comment]
Hi @nitin194 thanks for raising this issue. 

I see it is working for me.
I did Chrome->Bookmarks->Import bookmark -> Select from HTML file -> choose the file.
I see it is creating 2 folders with the name Kubernetes.  1 of them is empty but the second one has all the contents. So check both the folders. 
![unnamed](https://user-images.githubusercontent.com/14129300/111083119-13c67c00-84c9-11eb-964f-9278a28425a2.jpg)



Also, if you download the file locally and open the HTML file in browser, that should also work. You dont have to necessarily import the bookmarks.

**Comment by sunnyruziev** [comment]
I have same problem, after importing the file nothing is showing up.
